Feature 4
yurchenkosv/credential_storage pull request #5
Opened 2023-02-01 17:09 UTC by yurchenkosv

2023-02-03 18:51 UTC, kilchik requested changes

2023-02-03 18:51 UTC, kilchik commented on api/proto/gophkeeper.proto
> -  rpc GetCredentialsData(CredentialsDataRequest) returns (CredentialsData) {}
У тебя часть кода уже в main, поэтому не очень удобно было комментить в этом PR - сделал единый список

По структуре
Тебе наверное будет не очень удобно в такой плоской структуре добавлять пакеты для клиента и для сервера, я бы предложил верхнеуровнего их разграничить (типа /pkg/server и /pkg/client)

Логи (на этом этапе ты вероятно еще не успел, но на будущее)
Логи есть, но их прям надо пригладить (добавить user_id и прочие аттрибуты, без которых расследование инцидентов не получится)

https://github.com/yurchenkosv/credential_storage/blob/main/cmd/credentialsServer/server.go#L21 
Не нужна глобальная переменная

credStorageErrors - отдельный репозиторий под ошибки мне кажется избыточным (лучше инкапсулировать в пакет, связанный с их генерацией)

Вот таких конструкций быть не должно
```
	if err != nil {
		return nil, err
	}
```
Ошибки тщательно оборачиваем с префиксом, чтбы потом понимать, из какого места они триггернулись

Увидел, что данные в постгресе хранятся в plain text. Тут нужно продумать, как сделать так, чтобы злоумышленник, получивший базу с сервера, ей не смог слишком уж просто воспользоваться. С одной стороны здорово, что у тебя разные данные разбросаны по разным таблицам (с т з места для хранения), как обсуждали на вебинаре, с другой стороны - получается, что они хранятся без какой-либо обфускации. Я думаю, этот момент можно оставить на финальную проработку, чтобы успеть все остальное доделать
Ну и в чистом виде тоже желательно данные не передавать (добавь поддержку SSL например)

Моки я бы располагал в том же пакете, к которому они относятся, в поддиректории mocks

В остальном, отличное начало, но еще много всего нужно успеть)

2023-02-09 17:57 UTC, kilchik requested changes

2023-02-09 17:57 UTC, kilchik commented on internal/controllers/gophkeeperGRPCController.go
> +		Status:  200,
Лучше использовать статусы из пакета http

2023-02-09 17:57 UTC, kilchik commented on internal/repository/localBinaryRepository.go
> +func (r LocalBinaryRepository) Save(data []byte, filename string) (string, error) {
При работе с файловым хранилищем лучше всегда использовать интерфейсы Reader, Writer. В текущем контракте ты все равно будешь иметь все содержимое файла в памяти, но если потом возникнет потребность загружать файлы по http, ты сможешь легко читать содержимое из сокета непосредственно в файл, если в Save будет передаваться соединение или request.Body (который тоже поддерживает Reader интерфейс)

2023-02-09 17:57 UTC, kilchik commented on internal/repository/localBinaryRepository.go
> +	err := os.WriteFile(fileLocation, data, 0600)
Соответственно вот этот вызов заменится на io.Copy

2023-02-09 17:57 UTC, kilchik commented on internal/service/auth_test.go
> +	_, token, _ := auth.Encode(claims)
А чего ошибки игнорируем?

2023-02-10 07:10 UTC, yurchenkosv commented on internal/service/auth_test.go
> +	_, token, _ := auth.Encode(claims)
Глаз - алмаз )
Действительно, видимо посчитал на тот момент что для теста пойдет. Спасибо, поправлю.

2023-02-10 07:12 UTC, yurchenkosv commented on internal/controllers/gophkeeperGRPCController.go
> +		Status:  200,
Хм, но ведь тут не http, а GRPC. С другой стороны именно эмуляцией поведения http я тут и занимаюсь )
Ок, поправлю )

2023-02-10 07:14 UTC, yurchenkosv commented on internal/repository/localBinaryRepository.go
> +func (r LocalBinaryRepository) Save(data []byte, filename string) (string, error) {
Действительно, очень хорошая идея, спасибо.

2023-02-20 17:11 UTC, kilchik approved these changes

2023-02-21 17:14 UTC, merged